### ISSUE TITLE
events that hook choose() and close() would be nice

### ISSUE THREAD

**Issue by lutherism** [Kloudless/file-explorer#13]
We have to do some styling when the modal is open and closed. Specifically, we're adding a shadow frame to cover the background. Hooks into these UI events would be helpful.

**Comment by vinodc** [comment]
Hi @lutherism . I might be misunderstanding, but wouldn't the current `close` and `success` event handlers be sufficient to close the shadow frame in? They are invoked when the modal is closed.

In addition, if you are calling `choose()` via JS, you can open the shadow frame before/after the call. If you are using `choosify`, just set a click handler on the element passed in to `choosify` to open the shadow frame instead.

Does this work?

**Comment by lutherism** [comment]
Do you have a link to the 'close' event? There doesn't seem to be a 'close' event. We have to put our UI cleanup in three events: 'cancel', 'success', and 'error', to cover all the close states we could find.

**Comment by vinodc** [comment]
Apologies I meant `cancel` instead of `close`. Edited my post above to reflect the correction. That is correct that there are three events you would want to catch to do cleanup in. I'll look into adding a separate `close` event to always trigger regardless of the reason for closing.

**Comment by lutherism** [comment]
Thanks. Yea adding that consistent event will make our code a lot easier to maintain.

**Comment by lutherism** [comment]
As for the choose hook, you're right it's not as necessary. But it would allow us to be less concerned with when/where we call explorer.choose();

IE, a page creates an explorer instance, then any number of subviews can call explorer.choose() without having to know the specifics of what the page wants to do with it.

**Comment by vinodc** [comment]
Whoops, accidentally closed.

**Comment by vinodc** [comment]
Added in https://github.com/Kloudless/file-explorer/commit/3a70c56f512ff65a1c69a3eabb65703424831d20. This will be released within the week.

**Comment by lutherism** [comment]
Brilliant. Thanks.

**Comment by vinodc** [comment]
This has been released.
