### ISSUE TITLE
Save explorer fails to popup

### ISSUE THREAD

**Issue by lutherism** [Kloudless/file-explorer#15]
When I try to activate the save explorer I get the following error after waiting about 5 seconds from my explorer.save() call:

Uncaught TypeError: Cannot read property 'length' of undefined

this happens in the explorer.save function. During an internal callback, something doesn't provide a required argument.

I was able to fix it by replacing explorer.save with a function that provides a default argument like this:

```
var origSave = explorer.save

 explorer.save = function (o) {
    if (!Array.isArray(o)) o = [];
   origSave.call(this, o);
}
```

Not sure exactly the cause, or if this fix is fully valid. But it does get the popup working

**Comment by vinodc** [comment]
My recent changes to the documentation were incorrect. I've modified them to be more accurate in https://github.com/Kloudless/file-explorer/commit/ac76a147c307f63c09c01e1bd8f2d6a483f474d1 for the save() method: it takes in an array of files to save.

**Comment by lutherism** [comment]
OK I see. So we have to put the file array in both the constructor options, and the save options?

If I don't include the files list in the constructor call, I get a "No files to save" console.log  on .save(<files>), and it fails to open.

so this code works. It's intended that the files array is duplicated?

```
Kloudless.explorer({
  ...
  files: <files array>
}).save(<files array>);
``

**Comment by vinodc** [comment]
This looks like a bug with our race condition handling. We'll get a fix for this released to production by tonight. The files option in the constructor should not be necessary, but since the `save()` call is performed prior to the File Explorer being completely loaded, the timeout that eventually calls it does not appear to pass in the correct options.

**Comment by lutherism** [comment]
Good to know. Thanks!

**Comment by vinodc** [comment]
The fixes have been released.
