### ISSUE TITLE
How to see 'connected accounts' ?

### ISSUE THREAD

**Issue by frumbert** [Kloudless/file-explorer#162]
I have `Connected Accounts: 31 >= 30 hard limit. Please contact Support to proceed.`. 

On my applications dashboard at https://developers.kloudless.com/applications it says I have **4 all time connected accounts**. Seems pretty low. But I can't see anywhere that might list them.

On https://developers.kloudless.com/subscription there is no way to subscribe. https://kloudless.com/pricing/ does not exist.

My app only uses the chooser and saver with ONLY **Implicit Grant**. I use no authentication or other services.

**Comment by vinodc** [comment]
Hi @frumbert. I've sent you an email regarding your account.
