### ISSUE TITLE
IE9 prompts user to Stay or Leave page when uploading from My Computer in Kloudless

### ISSUE THREAD

**Issue by jpplangrid** [Kloudless/file-explorer#31]
Steps to reproduce:

1. Use Internet Explorer 9 to log in.
2.  Add multiple local files to the Kloudless interface via My Computer.
3.  Click upload.

Expected: Upload starts immediately with no prompts.

Observed:  See screenshot, user is prompted to stay or leave the page.

![stay_or_leave_1-1](https://cloud.githubusercontent.com/assets/6867556/8115407/ec9b02e0-102f-11e5-8f90-65cafb4d68bf.png)

**Comment by vinodc** [comment]
Thanks. Confirmed that IE 9 triggers beforeunload on a variety of events ( https://msdn.microsoft.com/en-us/library/ms536907%28v=vs.85%29.aspx ). While this is okay, it leads to the observed behavior when combined with the condition at https://github.com/Kloudless/file-explorer/blob/master/src/explorer/js/app.js#L958

**Comment by vinodc** [comment]
We've disabled this behavior for IE < 11 for now: e75384bce12811d96c9de8ff2fab7bc349c698a0 . I'll update this issue when this is released.

**Comment by vinodc** [comment]
This has been released.

**Comment by jpplangrid** [comment]
Thanks @vinodc!
