### ISSUE TITLE
Dropbox sort flips as you go through multiple levels of subfolders

### ISSUE THREAD

**Issue by jpplangrid** [Kloudless/file-explorer#32]
Reproduced in Google Chrome, 43.0.2357.124 (64-bit)
Steps to reproduce:

1.  Using the file explorer, connect to Dropbox.
2.  Go to a folder with a lot of nesting layers (see structure below).
3.  Navigate to deepest level of heirarchy.

Structure:  Folder 1> Folder 1a> Folder 1b> Folder 1c. 

Expected:  Sorting stays consistent on all levels.

Observed:  Sorting flips as you go from folder to folder.

**Comment by vinodc** [comment]
Resolved in https://github.com/Kloudless/file-explorer/commit/3e38bd6edc791bdeffa668c6035952c4383791fc I'll update this issue when the fix is released.

**Comment by vinodc** [comment]
This has been released.
