### ISSUE TITLE
Second connection seems to fail in Internet Explorer 9, 10, and 11

### ISSUE THREAD

**Issue by jpplangrid** [Kloudless/file-explorer#33]
Steps to reproduce:

1.  In Internet Explorer 9, 10, or 11, connect to Dropbox in the Kloudless widget.
2.  Refresh page.
3.  In Kloudless menu, click to view your accounts.
4.  Click the Box icon.
5.  Provide credentials and connect.

Expected:  Box window closes and you see the file list of the service.

Observed:  The Box window closes, but the view does not update.  The Box service is not added to your list of accounts.  If you then refresh the browser and go back to Kloudless, you'll see Box is already successfully connected.

**Comment by vinodc** [comment]
Thanks for identifying these issues. We'll take a closer look at IE / sorting within the next 2 weeks.

**Comment by vinodc** [comment]
@jpplangrid A fix has been released for this. Please let me know if you continue to encounter any issues here.

**Comment by jpplangrid** [comment]
Thanks @vinodc!  I verified this works in IE9, IE10, and IE11.
