### ISSUE TITLE
Saver fails with https version of link.

### ISSUE THREAD

**Issue by lutherism** [Kloudless/file-explorer#34]
This link fails to save:

`https://public.plangrid.com/kloud/PlanGrid-is-processing-your-request.zip`

while this link works:

`http://public.plangrid.com/kloud/PlanGrid-is-processing-your-request.zip`

The first one recieves a 400 error from the kloudless endpoint. `Invalid URL: https…-your-request.zip`

The second link is processed fine.

**Comment by vinodc** [comment]
@lutherism Odd. I'm unable to reproduce via the endpoint. It could be a flaw with the File Explorer. Could I have the entire JSON error message you notice the endpoint returning?

**Comment by vinodc** [comment]
Scratch that. I have confirmed an SSL handshake failure from our server to the HTTPS URL endpoint. We'll look into why this is occurring, as well as whether this is restricted to the public.plangrid.com CloudFront endpoint.

**Comment by vinodc** [comment]
@lutherism Thanks for alerting us to this. We have resolved the issue and the https link should work now.
