### ISSUE TITLE
Select button doesn't handle double clicks/click spam

### ISSUE THREAD

**Issue by lutherism** [Kloudless/file-explorer#36]
If a user clicks the select button multiple times while the widget is processing, it will fire multiple "success" events and make calls to Kloudless api for every click.

Sending two network requests on a double-click doesn't seem right. This button should probably be locked while processing, or debounced.

**Comment by vinodc** [comment]
Thanks. Fixed in a7a51057c3656242b032ce2bfaaa39c24c895137 . While the button won't be disabled, the clicks won't go through. Will update this issue when it is released.

**Comment by vinodc** [comment]
This has been released.
