### ISSUE TITLE
Cancel button does not dismiss widget when no Flash or Silverlight is detected

### ISSUE THREAD

**Issue by jpplangrid** [Kloudless/file-explorer#38]
Steps to reproduce:

1.  In IE9, that does not have Flash or Silverlight installed, load the Kloudless file-explorer.
2.  When you see the error that you need Flash or Silverlight, click the "Cancel" button.

Expected: File explorer closes.

Observed:  No response.

**Comment by ahcai** [comment]
@jpplangrid Thanks for identifying this issue! We have a solution in the works and will update this ticket when it's released.

**Comment by vinodc** [comment]
Released with https://github.com/Kloudless/file-explorer/commit/fdd04ab2edf5cf1d3fd67f4910c703fb3c8d9a7a

**Comment by jpplangrid** [comment]
Thanks, works well!
