### ISSUE TITLE
Box multipart uploads fail

### ISSUE THREAD

**Issue by lutherism** [Kloudless/file-explorer#48]
I left an issue on the python lib repo as well. Our Box multipart uploads are failing to init. Is multipart box upload still supported?

Thanks,
-Alex

**Comment by vinodc** [comment]
Hi Alex. The File Explorer does not perform multipart uploads to Box as Box does not currently support uploading files in parts. The File Explorer hasn't performed multipart uploads to Box in the past. I've followed up separately via email regarding the backend uploads that I suspect you are referring to.
