### ISSUE TITLE
I don't always get a bearer_token

### ISSUE THREAD

**Issue by frumbert** [Kloudless/file-explorer#55]
I've specified `retrieve_token` in my explorer setup but it's not *always* being returned. For instance, i'm triggering inside a click handler but not using chooserify - shouldn't matter, right?

	$(".toolbar").on("click", "a[data-action]", function (event) {
		event.preventDefault();
		var tgt = (event.target.nodeName.toUpperCase()=="A") ? event.target : event.target.parentNode, // handle clicking icon inside link
			id = tgt.getAttribute("data-fileid");
		switch (tgt.getAttribute("data-action")) {
			case "upload-kloudless":
		var inst = window.Kloudless.explorer({
			"app_id": KLOUDLESS_APP_ID,
			"flavor": "chooser",
			"retrieve_token": true
		});
		inst.on("success", function (files) {
			console.log("files", files);
			var xhr = new XMLHttpRequest();
			xhr.open("GET", "https://api.kloudless.com/v0/accounts/" + files[0].account + "/files/" + files[0].id + "/contents", true);
			xhr.setRequestHeader("Authorization", "Bearer " + files[0].bearer_token.key);
			xhr.responseType = "arraybuffer";
			xhr.onload = function(oEvent) {
				if (xhr.status === 200) {
					var content = new Blob([xhr.response], {type: files[0].mime_type});
					myHandler.HandleCloudUpload(files[0].name, content, files[0].mime_type);
				}
			};
			xhr.send();
		});
		inst.choose();
       	break;
       // etc

I'm trying to download a file (in this case from Dropbox) and then pass it onto my external handler. To do this requires the bearer token. It seems that if I perform the code above once, and select a file - it is downloaded fine once. If I then trigger the same code again (click the button on the toolbar a second time) then Chooser appears and lets me select the file - but the `bearer_token` is now missing from the files array that it returns.

Click it five more times, and it will return properly four of those times and then not the fifth. So `bearer_token` doesn't seem like it can be relied upon, or my code is doing something weird. Any pointers?

**Comment by vinodc** [comment]
Hi @frumbert. Certainly odd. It could be a race condition. Could you move both the `explorer()` initialization as well as the `inst.on()` success handler outside of the `$("toolbar").on()` click handler? They would only need to be set once. The `choose()` call can remain within, to launch the chooser. Please let me know if that helps.

**Comment by frumbert** [comment]
I got sidetracked and finally came back to this! Yes, removing the binding from inside the "on" and just ensuring that I only set the `explorer` once means I get a `bearer_token` each time now. Great!

**Comment by frumbert** [comment]
Some months later, the problem is still intermittantly occuring. When I move the initialisation of explorer outside the event, I get a 404 warning on the console (no blocking error, which is ok) and the bearer_token usually gets set. But still not always.
