### ISSUE TITLE
link_options ignores direct parameter

### ISSUE THREAD

**Issue by mandemeskel** [Kloudless/file-explorer#57]
When I initialize explorer with the following parameters explorer creates a link with the right expiration date and state but direct is set to false.
`     

        link: true,
        link_options: 
        {
            direct: true,
            expiration: expiration_date.toISOString(),
            active: true
        },
`

The account is on Google Drive with normal access -admin access has the same result-, any ideas?

----

On further inspection of the request that the file explorer made I found this payload:

```
active: true
direct: false
expiration: "2017-04-23T06:33:59.264Z"
file_id: [FILE_ID]
```

Everything in the request body is accurate except direct, which should be true, is set to false.
Something in the library is forcing direct to be false.

**Comment by vinodc** [comment]
Fixed! Thanks for pointing this out.
The new version has been released.
