### ISSUE TITLE
Possible IE9 bug (console?)

### ISSUE THREAD

**Issue by robrobbins** [Kloudless/file-explorer#6]
Testing on IE9 I have just seen the familiar "works only with dev tools open" issue. In my experience the usual cause of this is `console.log` statements without a shim for the non-existent console object in IE9. 

Solution is to simply polyfill console if not there.

thanks

**Comment by robrobbins** [comment]
Any news on shimming those?

**Comment by robrobbins** [comment]
Perhaps is an issue with `loglevel` https://github.com/pimterry/loglevel

Our case is that we see it work with console open only.

**Comment by chriskuehl** [comment]
Thanks for the report -- I'm looking at this today, and will try to get a fix out ASAP.

**Comment by robrobbins** [comment]
(thumbsup)

As you can probably already know, this is only seen in the *Actual* POS that is IE9. Emulated 9 via 10/11/12 does not display this behavior.

**Comment by chriskuehl** [comment]
This should be fixed by 016a9573f2. We've deployed it to the CDN as well -- can you let us know if this fixes the issues you were experiencing? Thanks again!
