### ISSUE TITLE
Do/will you support "Save" instead of "Save as..."?

### ISSUE THREAD

**Issue by nathancarter** [Kloudless/file-explorer#61]
First:  Very cool library!  I'm very interested in it.

The demo applications, upon clicking "Save file," require you to choose the location in which to save the file.  So my question:  **Is it currently possible/documented (or is it a planned future feature) for the application to remember where the last file was saved, and re-save a new version over top of it?**

That would be ideal for editor applications, in which the user is editing a file and regularly saving (or the application is regularly auto-saving).

**Comment by vinodc** [comment]
Hi @nathancarter Thanks for the words of appreciation. Yes that is possible. Set `retrieve_token` to `true` in the configuration options for the File Explorer, so your front-end/back-end service can make API requests authorized with the Bearer token. Your application can then use file update API endpoint ([docs](https://developers.kloudless.com/docs/v1/storage#files-update-file-content)) to upload the updated file contents. If you do not have the file content and instead want to upload via a URL, use the upload endpoint ([docs](https://developers.kloudless.com/docs/v1/storage#files-upload-a-file)) with the URL, but set `overwrite` to `true` so it updates the existing file.

Your domain must be white-listed on the App Details page to retrieve the token.

**Comment by nathancarter** [comment]
Thank you for the quick reply!  That's great to hear.  Even though I don't understand it all yet (since I haven't started tinkering with Kloudless yet, so I haven't learned the ins and outs of the API) this gives me confidence that I should give it a try, and I can return here when I need to learn how to do this.  Thanks again.

**Comment by nathancarter** [comment]
After digging a bit...I note that the docs suggest doing this via `curl` on the command line.  My application is entirely client-side.  Can this be done with AJAX and CORS or will api.kloudless.com reject an AJAX request of this type?  Furthermore, is there a JavaScript API to accomplish this same task?

**Comment by vinodc** [comment]
@nathancarter HTTP requests via ajax would definitely work and won't be rejected due to CORS. You can reference our HTTP API documentation for how to perform the ajax request. We use curl to provide an example, but the HTTP request can be made from any client-side application.

**Comment by nathancarter** [comment]
Nice!

**Comment by nathancarter** [comment]
Just to close the loop on this, the reason I ended up not using Kloudless in the end is that I'm generating the content to save within the editor itself (obviously) rather than finding it somewhere as a URL on the Internet.  And yet the Kloudless API doesn't support base-64-encoded data URIs, so I can't transmit the data directly to Kloudless from my client-side app.  But thanks for all the help along the way!

**Comment by david-thorman** [comment]
@nathancarter I am sorry to hear that you ended up not using Kloudless. I am somewhat confused by your requirement for base64-encoded data URIs for upload purposes. Typically our users perform uploads by sending the raw binary file contents in the request body or via multi-part encoded form. Could you clarify that requirement a bit more?

**Comment by nathancarter** [comment]
I was essentially looking for a way to send data generated in the browser (e.g., the user typing a document into an editor in the page, then wanting to save that content) to Kloudless.  Since I saw that Kloudless accepted URLs, the first thing that came to mind was to send a data URI containing the user's data.  All the other examples I came across seemed to require some kind of server back-end in the app that wanted to access Kloudless, whereas my app is client-side only.  Is there a different approach you'd recommend for client-side-only apps?  Perhaps you have a pure JavaScript example of the binary upload you're describing?

**Comment by david-thorman** [comment]
I am not able to write up a full example at the current time, but if you are able to load your data into a Javascript `Blob` object, then that can be sent via an [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/send) using the `send` method. You should be able to set the relevant headers prior to sending as well.
