### ISSUE TITLE
Can I save a file using a base-64-encoded data URL?

### ISSUE THREAD

**Issue by nathancarter** [Kloudless/file-explorer#62]
Using the JavaScript library documented [here](https://github.com/Kloudless/file-explorer), if I try `explorer.save( [ { url : 'data:text/plain;base64,Tm90aGluZwpNdWNo', type : 'text/plain' } ] );` I get back an error that the URL is invalid.

Do you support base-64-encoded data URLs?  If so, what am I doing wrong?  If not, do you plan to support them in the future?

Thank you!

**Comment by vinodc** [comment]
@nathancarter If you possess the data in base64-encode form, you can decode and send the raw data to the upload endpoint as a binary upload, rather than an upload from a URL. URL-based uploads are most useful when the data is located at an external URL where it can be downloaded from.

**Comment by vinodc** [comment]
It appears I misunderstood the question. To clarify: base=64 encoded data URLs would not be supported via this endpoint as binary uploads are not supported via the File Explorer's build in save() mechanism. For that functionality, it is better to use the Chooser mode to prompt the user to select a folder to save data to, and then upload the data to that folder from your own JavaScript after the Bearer token (`retrieve_token` configuration parameter) and folder metadata is returned.

**Comment by nathancarter** [comment]
Unfortunately, this doesn't work for me.  I don't want the user to just choose the folder in which to save.  They should be able to specify the filename, just as with the Saver.  If the Saver error object told me the attempted path and filename, I could then proceed to handle that error with the REST API, but unfortunately, it does not.  I think, sadly, Kloudless will not work for me for this reason.  Thank you for your help, and I look forward to hearing if anything changes.
