### ISSUE TITLE
Storj.io gateway integration 

### ISSUE THREAD

**Issue by jschiarizzi** [Kloudless/file-explorer#69]
It would be cool if this service could integrate with some IPFS gateways and serve content from distributed sources.  I suggest starting with storj because it is fully S3 compatible.

**Comment by vinodc** [comment]
Hi @jschiarizzi . We do support S3-compatible connectors today, although we haven't tested storj specifically. We'll make a note of that internally though. Does the S3-compatible connector help with your use case?

**Comment by jschiarizzi** [comment]
Yes it probably does. Potentially this is something I could help with too, I'm currently experimenting with making a web gateway for storj.

more info on their s3 compatibility is here: https://github.com/storj/storj/wiki/S3-Gateway

**Comment by vinodc** [comment]
Thanks for letting us know. This appears to be an item the backend Kloudless API would need to support instead, although S3-compatible connectors are supported today. I'm closing this issue. for the File Explorer at the current time.
