### ISSUE TITLE
Not receiving bearer_token from file chooser

### ISSUE THREAD

**Issue by xjcoan** [Kloudless/file-explorer#72]
Hi, I'm looking to receive oauth bearer tokens back after successfully choosing a file location to store documents.  I'd like to save this key so I can sue it later when grabbing or saving files from another Kloudless window.  I'm able to successfully choose a service, login, etc. but the bearer token seems to be missing from the response on my callback.  I've set `retrieve_token` to true.

The code: 
```
var KloudlessFileChooser = function(domNode) {
  var explorer = window.Kloudless.explorer({
    app_id: MYAPPID,
    multiselect: false,
    computer: false,
    services: ['all'],
    types: ['folders'],
    retrieve_token: true
  });

  explorer.on('success', function(files) {
      // files doesn't contain bearer_token
  };

  explorer.choosify($(domNode)[0]);
};
```

Without the token, I get an error when attempting to use the file chooser elsewhere in the app: `failed to refresh filesystem Error: "Account data empty"`

Any help would be greatly appreciated!

**Comment by vinodc** [comment]
Hi! Have you set the domain you are launching the File Explorer from as a Trusted Domain on this page: https://developers.kloudless.com/applications/*/ui-tools/file-explorer?

**Comment by xjcoan** [comment]
Yep, that was the issue.  Had it pointing to our production URLs, but not to the NGROK instance I was using to test it locally.
Thanks!
