### ISSUE TITLE
Allow types string to be a RegExp

### ISSUE THREAD

**Issue by robrobbins** [Kloudless/file-explorer#8]
I have a use case where any permutation of a ".foo" extension's capitalization needs to be allowed. I can list them all:

    `['foo', 'FOO', 'Foo', 'fOo'...]`

Much better would be:

    `/[FfOo]{3}/`

**Comment by chriskuehl** [comment]
Are there any other use cases where a regex would be helpful for you? I'm wondering whether it might be cleaner to just switch to using a case-insensitive check of the file extensions -- that might be less surprising and better in the long run, if that would solve your problem?

**Comment by chriskuehl** [comment]
As of 691354adb we're now doing a case-insensitive compare of file extensions, which is consistent with the way the filtering in the upload dialog was being done. We'll have this deployed later today -- can you let us know if this will work for your use case? Thanks!

**Comment by robrobbins** [comment]
that'll work. thanks
