### ISSUE TITLE
jquery.ui.plupload.js contains an unprintable character

### ISSUE THREAD

**Issue by justinm** [Kloudless/file-explorer#86]
The following source code contains an unprintable character between `width:` and `self.options.thumb_width` that is causing Chrome to throw a syntax error when including the file explorer. See https://github.com/Kloudless/file-explorer/blob/350049a83192501496cc80f4452e28a69321225a/lib/plupload/jquery.ui.plupload/jquery.ui.plupload.js#L1073

**Comment by vinodc** [comment]
Thanks for pointing this out! It looks like this was added in from the original source that was included. We'll take some steps to resolve this soon.

**Comment by AllencxWang** [comment]
@justinm It should be addressed by the latest commit, thanks again for reporting the issue.
