### ISSUE TITLE
console logging

### ISSUE THREAD

**Issue by frumbert** [Kloudless/file-explorer#88]
is there any way to disable the console logging when initialising the explorer?

**Comment by AllencxWang** [comment]
Thanks for your input! We've created a ticket for this issue and will notify you when it's done.

**Comment by aaronbeall** [comment]
Same issue. We are also using [Pendo analytics](https://www.pendo.io/) and for some reason the explorer is absolutely flooding the console with messages (5 or 6 per second):
![image](https://user-images.githubusercontent.com/2973900/68358023-3088bd80-00e5-11ea-87a5-19c69d198521.png)

Any idea what this is and how I can suppress it?

**Comment by vinodc** [comment]
Hi @aaronbeall. We identified the issue as [this line](https://github.com/Kloudless/file-explorer/blob/master/src/explorer/js/app.js#L1608) that accidentally didn't respect the "debug" flag in the configuration. We normally run our development builds with debug turned on so didn't notice the anomaly in the logging continuing in production and are taking steps to address it application-wide.

This should be released to production in the near future.

**Comment by hong19** [comment]
@frumbert @aaronbeall This issue has been fixed. Currently, only warnings and errors will be displayed.
